"""Generate docs/PARAMETER_REGISTER.md from the code registry.

The register is generated, never hand-maintained, so it cannot drift from the code.
Run:  python3 analysis/gen_parameter_register.py
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "engine"))

from cce_engine.kernel import MODEL_VERSION  # noqa: E402
from cce_engine.params import Params, registry_as_records  # noqa: E402

HEADER = f"""# Parameter Register

**Generated by `analysis/gen_parameter_register.py` — do not edit by hand.**

Model version: `{MODEL_VERSION}` · Parameter set id: `{Params().fingerprint()}` ·
Parameters: {{n}}

Every parameter carries name, definition, units, default, plausible range, source status,
scope (common to all arms or society-specific), sensitivity priority and code location.

**Calibration status: every parameter is `not yet calibrated`.** None was fitted to
empirical data. Values are internally consistent stylised defaults. Where an empirical
source would normally appear and none has been established, the entry says
`not yet calibrated`; where information is absent, `not provided`.

Sensitivity priority drives the screening order in `STATISTICAL_ANALYSIS_PLAN.md` §7:
`high` parameters enter the Latin hypercube and Sobol designs, `medium` and `low` are
screened one-factor-at-a-time first.

"""


def fmt(v) -> str:
    s = str(v)
    s = s.replace("|", "\\|")
    return s if len(s) <= 90 else s[:87] + "..."


def main() -> None:
    recs = registry_as_records()
    out = [HEADER.format(n=len(recs))]
    for prio in ("high", "medium", "low"):
        rows = [r for r in recs if r["sensitivity"] == prio]
        out.append(f"\n## Sensitivity priority: {prio} ({len(rows)} parameters)\n")
        out.append("| Name | Definition | Units | Default | Range | Scope | Source | Code |")
        out.append("|---|---|---|---|---|---|---|---|")
        for r in rows:
            out.append("| `{name}` | {note} | {units} | `{default}` | `{range}` | {scope} | "
                       "{source} | `{code_location}` |".format(
                           name=r["name"], note=fmt(r["note"]), units=fmt(r["units"]),
                           default=fmt(r["default"]), range=fmt(r["range"]),
                           scope=r["scope"], source=r["source"],
                           code_location=r["code_location"]))
    path = os.path.join(os.path.dirname(__file__), "..", "docs", "PARAMETER_REGISTER.md")
    with open(os.path.abspath(path), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {os.path.abspath(path)} ({len(recs)} parameters)")


if __name__ == "__main__":
    main()
