#!/usr/bin/env node
/* =====================================================================
   CC / PORTFOLIO — REGENERATE THE STATIC FILES THAT MIRROR THE REGISTRY
   ---------------------------------------------------------------------
       node tools/sync-static.js            write the files
       node tools/sync-static.js --check    report drift, change nothing

   Two files repeat what data/projects.js already knows:

     map/index.html   the star map's list view. This is the version a
                      visitor without JavaScript gets, so it has to be
                      real HTML in the file rather than something a
                      script builds on load.
     sitemap.xml      one entry per public page.

   The site has no build step and is not getting one: nothing here runs
   at deploy time, and GitHub Pages serves the committed files as they
   are. This is a maintenance script you run when you change the
   registry, in the same spirit as updating a changelog. Forgetting is
   not silent — tools/validate-site.js runs the --check mode and fails.
   ===================================================================== */
"use strict";

const fs = require("fs");
const path = require("path");
const { ROOT, load, curated, primaryHref, escapeHtml } = require("./registry");

const SITE = "https://unicorn0-0cakes.github.io";
const check = process.argv.includes("--check");

const LINK_LABEL = {
  live: "Live", methods: "Methods", source: "Source",
  docs: "Docs", notebook: "Notebook", upstream: "Upstream"
};

/* ---------------------------------------------------------------------
   The star map's list view
   ------------------------------------------------------------------ */
function mapIndex(reg) {
  const isOffsite = (h) => /^https?:\/\//.test(h) && !h.startsWith(SITE);
  const rel = (h) => (h && h.startsWith("/") ? ".." + h : h);

  const groups = reg.navCategories().map((c) => {
    const list = curated(reg.byCategory(c.id));
    const items = list.map((p) => {
      const target = primaryHref(p);
      const links = Object.entries(p.links || {})
        .filter(([, href]) => href)
        .map(([k, href]) =>
          `<a href="${escapeHtml(rel(href))}"${isOffsite(href) ? ' rel="noopener"' : ""}>` +
          `${escapeHtml(LINK_LABEL[k] || k)}</a>`)
        .join("");
      const title = target
        ? `<a href="${escapeHtml(rel(target))}">${escapeHtml(p.title)}</a>`
        : escapeHtml(p.title);
      return "            <li>\n" +
             `              <span class="sm-index__title">${title}</span>\n` +
             (links ? `              <span class="sm-index__links">${links}</span>\n` : "") +
             "            </li>";
    }).join("\n");

    return `        <li style="--sm-accent: var(${c.accent})">\n` +
           `          <h3><a href="..${reg.catPath(c)}">${escapeHtml(c.name)}</a></h3>\n` +
           "          <ul>\n" + items + "\n          </ul>\n" +
           "        </li>";
  });

  return "\n" +
    "        <li>\n" +
    '          <h3><a href="../">Portfolio home</a></h3>\n' +
    "          <ul>\n" +
    '            <li><span class="sm-index__title"><a href="../about/">About</a></span></li>\n' +
    '            <li><span class="sm-index__title"><a href="../about/credentials/">Credentials</a></span></li>\n' +
    "          </ul>\n" +
    "        </li>\n" +
    groups.join("\n") + "\n      ";
}

/* ---------------------------------------------------------------------
   sitemap.xml — public pages only
   ------------------------------------------------------------------ */
function sitemap(reg) {
  const urls = ["/"];
  reg.navCategories().forEach((c) => urls.push(reg.catPath(c)));
  urls.push("/about/", "/about/credentials/", "/map/");

  /* Case studies live inside the registry, so they never have to be
     remembered separately. */
  reg.visible().forEach((p) => { if (p.caseStudy) urls.push(p.caseStudy); });

  /* Locally hosted builds — anything the registry points at on this site. */
  reg.visible().forEach((p) => {
    const live = p.links && p.links.live;
    if (live && live.startsWith("/")) urls.push(live);
  });

  const unique = [...new Set(urls)];
  return '<?xml version="1.0" encoding="UTF-8"?>\n' +
    "<!-- Generated by tools/sync-static.js. Do not edit by hand. -->\n" +
    '<urlset xmlns="http://www.sitemap.org/schemas/sitemap/0.9">\n'.replace("sitemap.org", "sitemaps.org") +
    unique.map((u) =>
      "  <url>\n" +
      `    <loc>${SITE}${u}</loc>\n` +
      `    <priority>${u === "/" ? "1.0" : u.split("/").filter(Boolean).length > 1 ? "0.6" : "0.8"}</priority>\n` +
      "  </url>").join("\n") +
    "\n</urlset>\n";
}

/* ------------------------------------------------------------------ */
function between(text, startMark, endMark, replacement) {
  const s = text.indexOf(startMark);
  const e = text.indexOf(endMark);
  if (s === -1 || e === -1) throw new Error("markers not found: " + startMark);
  return text.slice(0, s + startMark.length) + replacement + text.slice(e);
}

function main() {
  const reg = load();
  const results = [];

  const mapFile = path.join(ROOT, "map", "index.html");
  const mapSrc = fs.readFileSync(mapFile, "utf8");
  const mapOut = between(mapSrc,
    "<!-- CC:MAP-INDEX:START -->", "<!-- CC:MAP-INDEX:END -->", mapIndex(reg));
  results.push(["map/index.html", mapFile, mapSrc, mapOut]);

  const smFile = path.join(ROOT, "sitemap.xml");
  const smSrc = fs.existsSync(smFile) ? fs.readFileSync(smFile, "utf8") : "";
  results.push(["sitemap.xml", smFile, smSrc, sitemap(reg)]);

  let drifted = 0;
  for (const [label, file, before, after] of results) {
    if (before === after) { if (!check) console.log("  unchanged  " + label); continue; }
    drifted++;
    if (check) { console.error("  OUT OF DATE  " + label); continue; }
    fs.writeFileSync(file, after);
    console.log("  written    " + label);
  }

  if (check && drifted) {
    console.error("\n" + drifted + " generated file(s) do not match the registry.");
    console.error("Run:  node tools/sync-static.js\n");
    process.exit(1);
  }
  if (check) console.log("Generated files are in sync with the registry.");
}

main();
